name: Simulate Battle and Generate Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Battle Simulation
        run: python simulate_battle.py

      - name: Convert Text to Image
        run: python txt_to_img.py

      - name: Commit updated state and image
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add battle_state.txt battle_map.txt battle_map.png
          git commit -m "Update battle simulation and image [skip ci]" || echo "No changes to commit"
          git push
